# Generated by Django 5.1.6 on 2025-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patientprofile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('canceled', 'canceled'), ('no-show', 'no-show')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
