# Generated by Django 5.1.6 on 2025-04-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_doctorprofile_bio_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
